paths:
  train_mask_dir: "data/masks/train"
  test_mask_dir: "data/masks/test"
  preprocessed_train_dir: "preprocessed/train"
  preprocessed_test_dir: "preprocessed/test"
  sentinel_data_dirs:
    - "data/2019-09-01 - 2019-09-30/sentinel_2"
    - "data/2020-09-01 - 2020-09-30/sentinel_2"
  log_dir: "logs"

filenames:
  masks: "mask_{id}.tif"
  images: "geojson_{id}.tif"
  block: "block_{id}.npz"

channels:
  current: ["B01", "B02", "B03", "B04", "B05", "B06", "B07", "B08", "B8A", "B09", "B11", "B12"]
  selected: ["B02", "B03", "B04", "B08", "B05", "B06", "B07", "B11", "B12", "B8A"]

dataset:
  target_size: [224, 224]
  radius: 2
  sampling_rate: 1
  block_size: 100000
  num_workers: 0

training:
  batch_size: 32
  epochs: 10
  warmup_epochs: 5
  scheduler:
    type: CosineAnnealingLR
    T_max_factor: 1

optimizer:
  type: Adam
  params:
    lr: 0.0005
    weight_decay: 0.0001

model:
  pretrained_name: "BIFOLD-BigEarthNetv2-0/resnet50-s2-v0.2.0"
